### ISSUE TITLE
feedback for part 1

### ISSUE THREAD

**Issue by samstephen** [Patmando73/07-20-rest-atomics#2]
https://infinite-citadel-3463.herokuapp.com/home

**Comment by sumeetjain** [comment]
# Very Important:
- [x] You should be able to describe clearly, simply, and comprehensively why this form does not have an `action` attribute. And you should be able to defend your decision to not give it one. https://github.com/Patmando73/07-20-rest-atomics/blob/master/views/users/new.erb#L1

# Medium Importance:
- [x] Should be organized into separate controllers. (Decide for yourself what organization makes sense.) https://github.com/Patmando73/07-20-rest-atomics/blob/master/controllers/main.rb
- [x] Should be inside `body`: https://github.com/Patmando73/07-20-rest-atomics/blob/master/views/layout.erb#L16

# Minor Things:
- [x] Extra lines: https://github.com/Patmando73/07-20-rest-atomics/blob/master/models/user.rb#L1-L2
- [x] Extra space: https://github.com/Patmando73/07-20-rest-atomics/blob/master/models/user.rb#L3
- [x] Shouldn't have spaces around `=` sign: https://github.com/Patmando73/07-20-rest-atomics/blob/master/views/users/edit.erb#L1

**Comment by Patmando73** [comment]
Very Important - We do not have an action set to this form because we are using Javascript to run the information put in the form through the post -  "/users" which adds the user. We do this to keep from having to go to a new page when submitting the data of the form.

**Comment by sumeetjain** [comment]
> We do this to keep from having to go to a new page when submitting the data of the form.

There is a better way to prevent the form from taking you to a new page. Please implement that and post a link to the file I should look at to see the updated code.

**Comment by samstephen** [comment]
so the way our javascript adds a user works - if we prevented the default action from occurring on the page when the user clicks the "Create a New Account" button, the js says to ignore the action of the form and add it using the js. If the js isn't enabled the action of the form will route the user to the json showing the users created. We can prevent that too with a redirect to the home.

Is that what your saying is the better way?

**Comment by sumeetjain** [comment]
Yup.

**Comment by Patmando73** [comment]
https://github.com/Patmando73/07-20-rest-atomics/blob/master/views/users/new.erb

Updated add user form
